create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    salt text not null,
    real_name text not null,
    gender text default 'male',
    phone text not null,
    email text default '',
    role text default 'user',
    status text default 'normal',
    created_at text not null,
    updated_at text not null
);

create table if not exists public.health_reports (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    report_no text default '',
    report_title text not null,
    summary text not null,
    risk_level text default 'normal',
    status text default 'normal',
    report_date text not null,
    heart_rate integer,
    blood_pressure text default '',
    blood_oxygen integer,
    temperature numeric,
    suggestions text default '',
    face_id text default '',
    health_data_id text default '',
    generate_method text default 'normal',
    created_at text default '',
    updated_at text default ''
);

create table if not exists public.face_records (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    user_name text default '',
    recognition_time text not null,
    similarity numeric default 0,
    device_name text default '',
    result text default 'normal',
    health_status text default 'normal',
    location text default '',
    image_path text default ''
);

create table if not exists public.health_data (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    user_name text default '',
    height_cm numeric,
    weight_kg numeric,
    heart_rate integer,
    systolic_bp integer,
    diastolic_bp integer,
    blood_oxygen integer,
    temperature numeric,
    risk_level text default 'normal',
    face_id text default '',
    analysis_result text default '',
    remarks text default '',
    measured_at text not null
);

create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    category text default 'normal',
    status text default 'normal',
    published_at text not null,
    is_top integer default 0,
    views integer default 0,
    updated_at text default ''
);

create table if not exists public.carousel_items (
    id bigint generated by default as identity primary key,
    title text not null,
    subtitle text default '',
    image_url text default '',
    link_url text default '',
    sort_order integer default 0,
    status text default 'normal',
    created_at text default ''
);

create table if not exists public.app_meta (
    key text primary key,
    value text not null
);

alter table public.users disable row level security;
alter table public.health_reports disable row level security;
alter table public.face_records disable row level security;
alter table public.health_data disable row level security;
alter table public.announcements disable row level security;
alter table public.carousel_items disable row level security;
alter table public.app_meta disable row level security;
