services:
  - type: web
    name: face-health-analysis
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node --no-warnings server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 22
      - key: RENDER
        value: "true"
      - key: DB_PATH
        value: /tmp/app.db
